### ISSUE TITLE
indicator design

### ISSUE THREAD

**Issue by shihyeon** [najoan125/KoreanPatch-multiLoader#11]
이런 디자인은 어떤가요?

![image](https://github.com/user-attachments/assets/511ba8b6-9db9-4c69-b483-c10e829bd067)
![image](https://github.com/user-attachments/assets/f2f085b8-fc61-42db-8855-242333e161db)
![image](https://github.com/user-attachments/assets/2f09ef10-07e6-40a3-a976-2390850e6dc8)
![image](https://github.com/user-attachments/assets/dbbeffbc-b1d3-458b-ae35-d052c5675456)

**Comment by najoan125** [comment]
테두리가 있는 지금이 더 가독성이 좋은 것 같아요. 근데 모서리가 너무 각져있어서 라운딩 처리 할까 고민중이긴 합니다
