### ISSUE TITLE
Amendments 모드와 호환 문제

### ISSUE THREAD

**Issue by ISTP7880** [najoan125/KoreanPatch-multiLoader#14]
책과 깃펜에서 글을 작성 할때 영어는 안쳐지고 한국어는 게임 충돌이 발생합니다!

**Comment by ISTP7880** [comment]
확인 결과 독서대 쪽만 그렇네요.

**Comment by najoan125** [comment]
다음 주 내로 고칠 수 있도록 노력해볼게요!

**Comment by najoan125** [comment]
늦어서 죄송합니다... 일단 JEI 호환 문제와 함께 코드 상으로는 이 문제도 함께 해결했습니다. 이번 주 내로 출시하도록 하겠습니다.

**Comment by ISTP7880** [comment]
기다리던 중 반가운 소식이네요...! 감사합니다!
아 그리고 1.21.3과 1.21.4 버전도 올려 주시면 감사하겠습니다!

**Comment by najoan125** [comment]
1.6.11 버전이 출시되었으며, 해당 버그가 해결되었습니다. 
1.21.4도 지원하도록 변경하였습니다 (Fabric 1.21.4의 경우, 이전 버전과 다르게 Fabric API가 꼭 필요합니다)

**Comment by ISTP7880** [comment]
증상이 여전해요 이건 GUI 비율 문제로 나타나는 듯 해요

**Comment by ISTP7880** [comment]
특히 2, 4에서 나타났던걸로 기억해요

**Comment by najoan125** [comment]
혹시 마인크래프트 버전과 모드 로더가 어떤건지 알 수 있을까요?

**Comment by najoan125** [comment]
제가 해결한 버그는 한글 상태에서의 크래시와, 색깔 코드가 적용되지 않는 버그입니다. 영어 상태에서 입력되지 않는 문제는 한글채팅 모드를 뺐을때도 증상이 그대로여서 해당 모드의 자체 버그로 판단했습니다

**Comment by ISTP7880** [comment]
Fabric, 1.21.1 입니다.

**Comment by ISTP7880** [comment]
아 amendments 모드가 2개월째 업데이트 소식이 없더라고요...

**Comment by najoan125** [comment]
알려주셔서 감사합니다! 빠른 시일 내에 고치도록 하겠습니다

**Comment by najoan125** [comment]
https://github.com/user-attachments/assets/9105d36d-adcb-439a-a752-f769e9f9d565

GUI 비율 2, 4 모두 해봐도 잘 되는 것 같아요...
정확히 어떻게 해야 문제가 일어나는지 알려주실 수 있나요?

**Comment by ISTP7880** [comment]
아무래도 제가 가진 모드가 310개 였는데 그중에서 뭔가 충돌이 일어난 것 같네요

**Comment by ISTP7880** [comment]
지금은 버전을 1.21.3으로 올려서 잘 모르겠습니다 ㅠㅠ
