### ISSUE TITLE
JEI 모드와 호환 문제

### ISSUE THREAD

**Issue by Jangtella** [najoan125/KoreanPatch-multiLoader#15]
JEI- 1.20.1 -forge 15.20.0.105
koreanpatch -forge 1.6.10+mc1.20.1
JEI 모드 검색기능에 한글자밖에 입력이 안됩니다
![javaw_ihQyL1mq7G](https://github.com/user-attachments/assets/9da2e68a-bce9-4125-9e61-f2a51fc50825)

**Comment by najoan125** [comment]
다다음주 까지 고쳐볼게요

**Comment by najoan125** [comment]
![image](https://github.com/user-attachments/assets/a78aff45-983b-4c2d-ae52-a5bdd98de46d)
코드 두 줄 제거하니까 고쳐지긴 하는 것을 발견했습니다. 아마 1.6.11로 출시될 거 같아요. 
이번 주 까지는 최대한 출시해보도록 하겠습니다! 혹시나 또 다른 버그가 발생하게 된다면 또 Issue 남겨주세요!

**Comment by najoan125** [comment]
1.6.11 버전이 출시되었으며, 해당 버그가 해결되었습니다
