### ISSUE TITLE
EditBox가 아닌 텍스트박스에서 IME가 활성화된 후 한글 상태일 때 비활성화가 되지 않습니다.

### ISSUE THREAD

**Issue by shihyeon** [najoan125/KoreanPatch-multiLoader#8]
1. EditBox가 아닌 텍스트 박스에 커서를 가져감
2. 한글로 바꾸어 IME를 킴
3. (한글 입력)
4. 한글인 상태에서 스크린을 닫음
5. 결과: IME 활성화 상태

(영문일 경우)
4. 영문으로 바꾸고 스크린을 닫음
5. IME 비활성화 상태

http://naver.me/FZ2X5mny

**Comment by najoan125** [comment]
Editbox에서는 문제가 없나요?

**Comment by shihyeon** [comment]
네, IME가 켜지는 텍스트박스에서만 저런 현상이 나타납니다.

**Comment by najoan125** [comment]
근데 영상 초반부분에도 ime가 비활성화 되지 않은것으로 보이는데 한번 저런 버그가 걸리면 껐다 키지 않는한 계속 ime가 활성화되어 있는건가요?

**Comment by shihyeon** [comment]
IME가 켜지는 텍스트박스에서 영문 상태로 만들면 정상적으로 IME가 비활성화됩니다.

Reese sodium option의 텍스트박스는 IME가 켜지는 박스입니다.

**Comment by shihyeon** [comment]
보니까 IME 활성화 하는 버전부터 있었던 버그로 보입니다.

**Comment by najoan125** [comment]
일단 제가 내일 테스트 해보고 원인을 찾아볼게요

**Comment by najoan125** [comment]
확인해보니 상자 GUI에서는 IME가 활성화되는게 맞네요
제가 IME 기능 추가할 때 Editbox가 없는 곳에서는 자동으로 무조건 IME가 활성화되도록 했습니다

**Comment by najoan125** [comment]
추후에 설정 GUI에서 자동 활성화를 켜고 끌 수 있게 변경할 예정입니다

**Comment by najoan125** [comment]
일단 상자 GUI와 서바이벌 Inventory에서 IME가 자동 활성화되지 않도록 수정하겠습니다.

**Comment by shihyeon** [comment]
추후 주민 거래 스크린 `MerchantScreen.class`도 추가하면 좋을 것 같습니다.
