### ISSUE TITLE
제작대에서 한글 입력이 안됩니다.

### ISSUE THREAD

**Issue by korea-1027** [najoan125/KoreanPatch-multiLoader#9]
잘 사용하고 있는데,
제작대에서 조합법을 검색을 할때 영어 밖에 사용이 안됩니다.

**Comment by najoan125** [comment]
제작대 등 한글입력이 안되는 곳에서 정상 작동하도록 최대한 빠르게 수정하겠습니다!

참고로, 한글 안될때 ime변환키로 ime활성화 하시면 정상적으로 입력 가능해요. Ime변환키는 조작키 설정에서 변경 가능하고, 기본적으로 컨트롤(Ctrl) 키와 i키를 같이 눌러 변경 가능해요.

**Comment by najoan125** [comment]
모드 버전 1.6.9 기준, 마인크래프트 1.21에서는 잘 작동되는 것으로 보이는데, 혹시 어떤 버전에서 해보셨을까요?
